name: Go

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v -o ue4pak .

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Install Satisfactory Dedicated Server
        run: steamcmd +login anonymous +force_install_dir $GITHUB_WORKSPACE/SatisfactoryDedicatedServer +app_update 1690800 validate +quit && ls -lR

      - name: Test
        run: go run main.go test --pak ./SatisfactoryDedicatedServer/FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak --colors --log info --assets "*"
